version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile-frontend
    ports:
      - "3383:3383"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile-backend
    ports:
      - "3380:3380"
    env_file:
      - ./backend/.env
